Args = --initialize-at-build-time=org.apache.xmlbeans.metadata.system,org.apache.poi.schemas.ooxml.system.ooxml.TypeSystemHolder \
  --initialize-at-run-time=com.jcraft.jsch.JSch,com.jcraft.jsch.Session,com.jcraft.jsch.ChannelSftp \
  --initialize-at-run-time=org.apache.poi.util.LocaleUtil,org.apache.poi.util.RandomSingleton,org.apache.poi.openxml4j.util.ZipSecureFile,org.apache.poi.ooxml.POIXMLTypeLoader,org.openxmlformats.schemas \
  --initialize-at-run-time=io.grpc.xds.internal.security \
  -H:DeadlockWatchdogInterval=120 \
  --enable-url-protocols=http,https
