-- R1 (identidad de pago en la intención de dispatch del camino de LISTA en memoria):
-- el ledger mt101_pay_dispatch_intent (V87) hacía el claim por dispatch_key = transport|conn|correlationKey
-- (la idempotency key del banco). Un re-request bajo la MISMA clave se reportaba ALREADY_SENT sin comparar el
-- PAYLOAD: si dos pagos DISTINTOS resolvían la misma clave (p.ej. :20: reutilizado con otro monto/beneficiario),
-- el segundo se silenciaba (accepted) SIN enviarse. Nunca duplica pago, pero puede callar uno válido.
--
-- payload_hash guarda el SHA-256 del rawPayload EXACTO que recibe el banco (lo mismo que envían REST/SFTP), fijado
-- al reclamar. En un claim bloqueado (SENT/UNCERTAIN) se compara: mismo hash -> idempotente (probado, no inferido);
-- hash distinto -> colisión de clave con OTRO pago -> conflicto (no se reporta enviado; exige conciliación). Un
-- payload_hash NULL (filas previas a esta identidad) no se puede probar igual -> se trata como conflicto seguro.
alter table mt101_pay_dispatch_intent add column payload_hash varchar(64);
