# Imagen NATIVA del plugin demo gRPC (Quarkus). Espera el runner ya construido:
#   mvn -B clean package -Pnative -Dquarkus.native.container-build=true
# Runtime UBI9 (glibc 2.34) para emparejar con el builder Mandrel jdk-25.
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
RUN chown 1001 /work && chmod g+rwX /work && chown 1001:root /work
ARG RUNNER=target/*-runner
COPY --chown=1001:root --chmod=0755 ${RUNNER} /work/application
ENV PLUGIN_GRPC_PORT=50061
EXPOSE 50061
USER 1001
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.grpc.server.host=0.0.0.0"]
